import { soma, subtracao, multiplicacao, divisao, raizQuadrada, potencia } from "./calculosBasicos.js";
import { simplificarFracao, conversao } from "./conversoesEsimplificacoes.js";
import { equacaoPrimeiroGrau, equacaoSegundoGrau } from "./equacoes.js";
import { porcentagem, desconto, acrescimo } from "./percentuais.js";
import { regra3, regra3composta } from "./regra3.js";
import { mediaAritmetica, mediana, moda } from "./medias.js";

document.getElementById("btnSoma").addEventListener("click", (e) => { soma(); e.target.blur(); });
document.getElementById("btnSubtracao").addEventListener("click", (e) => { subtracao(); e.target.blur(); });
document.getElementById("btnMultiplicacao").addEventListener("click", (e) => { multiplicacao(); e.target.blur(); });
document.getElementById("btnDivisao").addEventListener("click", (e) => { divisao(); e.target.blur(); });
document.getElementById("btnPotencia").addEventListener("click", (e) => { potencia(); e.target.blur(); });
document.getElementById("btnRaiz").addEventListener("click", (e) => { raizQuadrada(); e.target.blur(); });
document.getElementById("btnFracao").addEventListener("click", (e) => { simplificarFracao(); e.target.blur(); });
document.getElementById("btnConversao").addEventListener("click", (e) => { conversao(); e.target.blur(); });
document.getElementById("btnEquacao1").addEventListener("click", (e) => { equacaoPrimeiroGrau(); e.target.blur(); });
document.getElementById("btnEquacao2").addEventListener("click", (e) => { equacaoSegundoGrau(); e.target.blur(); });
document.getElementById("btnPorcentagem").addEventListener("click", (e) => { porcentagem(); e.target.blur(); });
document.getElementById("btnAcrescimo").addEventListener("click", (e) => { acrescimo(); e.target.blur(); });
document.getElementById("btnDesconto").addEventListener("click", (e) => { desconto(); e.target.blur(); });
document.getElementById("btnRegra3").addEventListener("click", (e) => { regra3(); e.target.blur(); });
document.getElementById("btnRegra3Composta").addEventListener("click", (e) => { regra3composta(); e.target.blur(); });
document.getElementById("btnMedia").addEventListener("click", (e) => { mediaAritmetica(); e.target.blur(); });
document.getElementById("btnMediana").addEventListener("click", (e) => { mediana(); e.target.blur(); });
document.getElementById("btnModa").addEventListener("click", (e) => { moda(); e.target.blur(); });