import { soma, subtracao, multiplicacao, divisao, raizQuadrada, potencia } from "./calculosBasicos.js";
import { simplificarFracao, conversao } from "./conversoesEsimplificacoes.js";
import { equacaoPrimeiroGrau, equacaoSegundoGrau } from "./equacoes.js";
import { porcentagem, desconto, acrescimo } from "./percentuais.js";
import { regra3, regra3composta } from "./regra3.js";
import { mediaAritmetica, mediana, moda } from "./medias.js";

document.getElementById("btnSoma").addEventListener("click", soma);
document.getElementById("btnSubtracao").addEventListener("click", subtracao);
document.getElementById("btnMultiplicacao").addEventListener("click", multiplicacao);
document.getElementById("btnDivisao").addEventListener("click", divisao);
document.getElementById("btnPotencia").addEventListener("click", potencia);
document.getElementById("btnRaiz").addEventListener("click", raizQuadrada);
document.getElementById("btnFracao").addEventListener("click", simplificarFracao);
document.getElementById("btnConversao").addEventListener("click", conversao);
document.getElementById("btnEquacao1").addEventListener("click", equacaoPrimeiroGrau);
document.getElementById("btnEquacao2").addEventListener("click", equacaoSegundoGrau);
document.getElementById("btnPorcentagem").addEventListener("click", porcentagem);
document.getElementById("btnAcrescimo").addEventListener("click", acrescimo);
document.getElementById("btnDesconto").addEventListener("click", desconto);
document.getElementById("btnRegra3").addEventListener("click", regra3);
document.getElementById("btnRegra3Composta").addEventListener("click", regra3composta);
document.getElementById("btnMedia").addEventListener("click", mediaAritmetica);
document.getElementById("btnMediana").addEventListener("click", mediana);
document.getElementById("btnModa").addEventListener("click", moda);